<?php

/**
 * Autogenerated CRUD controller
 * Template version March 12th 2013
 */
class VoteController extends WE_Controller_Crud
{
	
	public function	indexAction () {
		$votes = Db::getTable('Vote')->getAll(true,false);
		$this->view->assign('votes',$votes);
		return $this->view->render();
	}
	
	public function	viewAction () {
		$voteId = $this->getRequest()->getGet('id');
		$vote = Db::getModel('Vote')->find($voteId);
		
		if ( !is_object($vote) ) {
			WE_Engine_Session::setFlash('De opgegeven vote bestaat niet.', 'error');
			$this->redirect($this->getRequest()->getSystemKey()."/vote");
		} else {
			$this->view->assign('vote',$vote);	
			return $this->view->render();
		}
	}

	public function	addAction () {
		if ($this->getRequest()->isPost()) {
			$vote = Db::getModel('Vote');
			$postdata = $this->getRequest()->getPost('vote');
			
			$vote->setEntry($postdata['entry']);
			$vote->setIp($postdata['ip']);
			$vote->setDate($postdata['date']);
			$vote->save();
			
			$id = $vote->getId();
			WE_Engine_Session::setFlash('De vote succesvol toegevoegd.', 'success');
			$this->redirect($this->getRequest()->getSystemKey()."/vote/view/$id");
		} else {
			return $this->view->render();
		}
	}
	
	public function	modifyAction () {
		if ($this->getRequest()->isPost()) {
			$vote = Db::getModel('Vote')->find($this->getRequest()->getGet('id'));
			$postdata = $this->getRequest()->getPost('vote');
			
			$vote->setEntry($postdata['entry']);
			$vote->setIp($postdata['ip']);
			$vote->setDate($postdata['date']);
			$vote->save();
			
			WE_Engine_Session::setFlash('De vote succesvol bewerkt.', 'success');
			$this->redirect($this->getRequest()->getSystemKey()."/vote/view/".$vote->getId());
		} else {
			$vote = Db::getModel('Vote')->find($this->getRequest()->getGet('id'));
			$this->view->assign('vote',$vote);
			return $this->view->render();
		}
	}
	
	public function	deleteAction () {
		$vote = Db::getModel('Vote')->find($this->getRequest()->getGet('id'));
		if ( !is_object($vote) ) {
			WE_Engine_Session::setFlash('Er is geen vote gevonden met het betreffende Id', 'error');
			$this->redirect($this->getRequest()->getSystemKey()."/vote");
		} else {
			$vote->delete();
			WE_Engine_Session::setFlash('De vote succesvol verwijderd.', 'success');
			$this->redirect($this->getRequest()->getSystemKey()."/vote");
		}
	}
	
}	
?>